python -m mlp_optimizer_bench.run_optim_bench \
  --dataset high_order_cls \
  --n-features 50 \
  --hidden-dims 256,256,256 \
  --optimizer adamw \
  --init-type spectral_mup_init \
  --init-sigma 0.02 \
  --lr 1e-2 \
  --weight-decay 0.1 \
  --max-steps 2000 \
  --device cuda