python -m mlp_optimizer_bench.run_optim_bench \
  --dataset high_order_cls \
  --n-features 50 \
  --hidden-dims 256,256,256 \
  --optimizer muon \
  --lr 3e-4 \
  --weight-decay 0.1 \
  --max-steps 2000 \
  --device cuda \
  --muon-momentum-beta 0.95 \
  --muon-use-nesterov \
  --muon-scale-mode align_adamw_rms \
  --muon-extra-scale-factor 1.0 \
  --muon-num-ns-steps 5 \
  --muon-coefficient-type quintic
